### ISSUE TITLE
Remove blog post from resources

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/ruby-self-readme#5]

**Comment by alexgriff** [comment]
@pletcher Which blog post should be removed, the [Flatrion blog post by Karin Masood](http://blog.flatironschool.com/programming-postmodernism-and-rubys-self/) or the one by [Yehuda Katz](http://yehudakatz.com/2009/11/15/metaprogramming-in-ruby-its-all-about-the-self/)?

**Comment by pletcher** [comment]
Ah, thanks for clarifying -- let's remove the Flatiron blog post.
